title: "Harikrishna Rao M"
email: "mohanrao@ualberta.ca"
description: >-
  PhD candidate at the University of Alberta working on data-driven alarm analytics and process control.
baseurl: ""
url: "https://hrmrao.github.io"
twitter_username: ""
github_username: "H-Rao"
minimal_mistakes_skin: "default"
search: true

author:
  name   : "Harikrishna Rao M"
  avatar : "/assets/img/profile.jpg"
  bio    : "PhD candidate, researcher in process control, alarm management, and decision support systems."

include:
  - _pages
  - assets

plugins:
  - jekyll-include-cache

# Navigation
nav:
  - title: "Bio"
    url: /index.html
  - title: "CV"
    url: /cv/
  - title: "CV of Failures"
    url: /failures/
  - title: "Interests"
    url: /interests/
  - title: "Contact"
    url: /contact/
